# html lang
language: en

# main menu navigation
menu:
  Posts: /
  Tags: /tags
  About: /about
#  Contact: /contact
#  Archives: /archives

copyright:
  name: mao

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/


# writing
untitled:
  name: Untitled

rss:
  path: atom.xml

utterances:
  enable: true
  repo: maodaisuki/blog
  issueTerm: pathname
  theme: github-light
  
mathjax:
  enable: true

mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true
  theme: default
  