# html lang
language: en

# main menu navigation
menu:
  Posts: /
  Tags: /tags
  Search:
# Search 注意和 header.ejs 中匹配
  About: /about
#  Contact: /contact
#  Archives: /archives

copyright:
  name: mao

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/


# writing
untitled:
  name: Untitled

rss:
  path: atom.xml

utterances:
  enable: true
  repo: maodaisuki/hexo-theme-maoblog
  issueTerm: pathname
  theme: github-light
  
mathjax:
  enable: true

mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true
  theme: default

search:
  path: search.xml
  field: post
  content: true

tag_generator:
  per_page: 0
  # 0 设置为每页不限制数量
  order_by: -date

# 控制文章信息
meta_time:
  enable: true

meta_tags:
  enable: true

analytics:
  enable: true
  gtag: AW-11373423003
