# html lang
language: en

# main menu navigation
menu:
  Home: /
  Tags: /tags
  About: /about
#  Contact: /contact
#  Archives: /archives

copyright:
  name: mao

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/


# stylesheets loaded in the <head>
stylesheets:
- /css/maoblog.css

# scripts loaded in the end of the body
scripts:
- /js/maoblog.js

utterances:
  enable: true
  repo: maodaisuki/hexo-theme-maoblog
  issueTerm: pathname
  theme: github-light

